services:
  - type: web
    name: aurex
    env: python
    buildCommand: |
      pip install -U pip wheel setuptools
      pip install -r requirements.txt
    startCommand: bash start
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: LOGGER_ID
        sync: false
      - key: OWNER_ID
        sync: false
      - key: STRING_SESSION
        sync: false
      - key: API_URL
        sync: false
